[package]
name = "zappy-server"
version = "0.1.0"
edition = "2021"
authors = ["nguiard", "sloquet"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
